### ISSUE TITLE
How to download Windows precompiled binary and Duku Sample Data?

### ISSUE THREAD

**Issue by bsekirarski** [NCAR/VAPOR-SupportPage#2]
How to download Windows precompiled binary and Duku Sample Data?

**Comment by sgpearse** [comment]
Hi, you can find it in the "Sample Data" section of the website.  Link below.

https://www.docs.vapor.ucar.edu/downloads.html#sample-data

**Comment by bsekirarski** [comment]
I obtain "Sign in with your CIT username and password" with no options to sign-in.
There is also no link to download precompiled Windows binary!

**Comment by sgpearse** [comment]
Thanks Boris.  It turns out that the sample data is currently in limbo as a "pre-published data set".  I've asked the admin to publish it, so it should be up shortly.  In the mean time, you can download the files from the link below.

https://drive.google.com/file/d/1URszKOOGV7paMkCV20gMdRko2JmRv25N/view?usp=sharing

Also, did you follow the download link that directs you to the survey?  After submitting the survey, you get forwarded to a selection of files to install Vapor with.  The windows binary installer is one of them.  It should look like the screenshot below.

![Screen Shot 2019-08-19 at 11 18 38 AM](https://user-images.githubusercontent.com/9522770/63285511-21773980-c273-11e9-9a18-77f7ca0674f1.png)

**Comment by bsekirarski** [comment]
Thanks a lot!
