### ISSUE TITLE
VAPOR install variable

### ISSUE THREAD

**Issue by brownwrap** [NCAR/VAPOR-SupportPage#4]
Some of the required 3rd party libraries need to be installed in non-standard locations, like glm. What environment variables are available when building from source?

**Comment by sgpearse** [comment]
Hi, we don't use any environment variables for our build process.  We also recommend downloading the third party libraries as a tar file, rather than building them yourself.  The libraries are listed in the following link, and you will need to extract them into a specific directory to link to them.  Make sure you download the correct libraries for your OS, and let us know if you have more questions.

https://www.docs.vapor.ucar.edu/downloads.html#building-from-source
