### ISSUE TITLE
I can't download the Install Vapor’s third party libraries from the official website.

### ISSUE THREAD

**Issue by luo981858** [NCAR/VAPOR-SupportPage#5]
Can you send the three party libraries of Windows to my mailbox?
My mailbox is zimingluo@foxmail.com
Regards,
Huihong

**Comment by sgpearse** [comment]
Huihong, is Google being blocked in your country?  We host the 3rd party libraries on Google Drive.  

NCAR uses GMail for our email service.  If we send your an email with the libraries, they will be also be sent through Google Drive, since they're larger than the 25MB attachment limit.

If Google isn't being blocked for you, you can download the libraries here: https://www.docs.vapor.ucar.edu/downloads.html#building-from-source
